
const SIGNUP_REQUEST="SIGNUP_REQUEST"
const SIGNUP_REQUEST_SUCESS="SIGNUP_REQUEST_SUCESS"
const SIGNUP_REQUEST_FAILUE="SIGNUP_REQUEST_FAILUE"

const LOGIN_REQUEST="LOGIN_REQUEST"
const LOGIN_REQUEST_SUCESS="LOGIN_REQUEST_SUCESS"
const LOGIN_REQUEST_FAILUE="LOGIN_REQUEST_FAILUE"

const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST"
const GET_PRODUCT_REQUEST_SUCESS="GET_PRODUCT_REQUEST_SUCESS"
const GET_PRODUCT_REQUEST_FAILUE="GET_PRODUCT_REQUEST_FAILUE"


const GET_PRODUCT_DETAILS_REQUEST="GET_PRODUCT_DETAILS_REQUEST"
const GET_PRODUCT_DETAILS_REQUEST_SUCESS="GET_PRODUCT_DETAILS_REQUEST_SUCESS"
const GET_PRODUCT_DETAILS_REQUEST_FAILUE="GET_PRODUCT_DETAILS_REQUEST_FAILUE"

const ADD_REVIEW_REQUEST="ADD_REVIEW_REQUEST"
const ADD_REVIEW_REQUEST_SUCESS="ADD_REVIEW_REQUEST_SUCESS"
const ADD_REVIEW_REQUEST_FAILUE="ADD_REVIEW_REQUEST_FAILUE"


export{
    SIGNUP_REQUEST,
    SIGNUP_REQUEST_SUCESS,
    SIGNUP_REQUEST_FAILUE,

    LOGIN_REQUEST,
    LOGIN_REQUEST_SUCESS,
    LOGIN_REQUEST_FAILUE,

    GET_PRODUCT_REQUEST,
    GET_PRODUCT_REQUEST_SUCESS,
    GET_PRODUCT_REQUEST_FAILUE,

    GET_PRODUCT_DETAILS_REQUEST,
    GET_PRODUCT_DETAILS_REQUEST_SUCESS,
    GET_PRODUCT_DETAILS_REQUEST_FAILUE,

    ADD_REVIEW_REQUEST,
    ADD_REVIEW_REQUEST_SUCESS,
    ADD_REVIEW_REQUEST_FAILUE
}