
const SIGNUP_REQUEST="SIGNUP_REQUEST"
const SIGNUP_REQUEST_SUCESS="SIGNUP_REQUEST_SUCESS"
const SIGNUP_REQUEST_FAILUE="SIGNUP_REQUEST_FAILUE"

const LOGIN_REQUEST="LOGIN_REQUEST"
const LOGIN_REQUEST_SUCESS="LOGIN_REQUEST_SUCESS"
const LOGIN_REQUEST_FAILUE="LOGIN_REQUEST_FAILUE"

const GET_REQUEST="GET_REQUEST"
const GET_REQUEST_SUCESS="GET_REQUEST_SUCESS"
const GET_REQUEST_FAILUE="GET_REQUEST_FAILUE"

export{
    SIGNUP_REQUEST,
    SIGNUP_REQUEST_SUCESS,
    SIGNUP_REQUEST_FAILUE,

    LOGIN_REQUEST,
    LOGIN_REQUEST_SUCESS,
    LOGIN_REQUEST_FAILUE,

    GET_REQUEST,
    GET_REQUEST_SUCESS,
    GET_REQUEST_FAILUE
}