
const SIGNUP_REQUEST = "SIGNUP_REQUEST"
const SIGNUP_REQUEST_SUCESS = "SIGNUP_REQUEST_SUCESS"
const SIGNUP_REQUEST_FAILUE = "SIGNUP_REQUEST_FAILUE"

const LOGIN_REQUEST = "LOGIN_REQUEST"
const LOGIN_REQUEST_SUCESS = "LOGIN_REQUEST_SUCESS"
const LOGIN_REQUEST_FAILUE = "LOGIN_REQUEST_FAILUE"

const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST"
const FORGET_PASSWORD_REQUEST_SUCESS = "FORGET_PASSWORD_REQUEST_SUCESS"
const FORGET_PASSWORD_REQUEST_FAILUE = "FORGET_PASSWORD_REQUEST_FAILUE"


const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
const RESET_PASSWORD_REQUEST_SUCESS = "RESET_PASSWORD_REQUEST_SUCESS"
const RESET_PASSWORD_REQUEST_FAILUE = "RESET_PASSWORD_REQUEST_FAILUE"

const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
const GET_PRODUCT_REQUEST_SUCESS = "GET_PRODUCT_REQUEST_SUCESS"
const GET_PRODUCT_REQUEST_FAILUE = "GET_PRODUCT_REQUEST_FAILUE"


const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST"
const GET_PRODUCT_DETAILS_REQUEST_SUCESS = "GET_PRODUCT_DETAILS_REQUEST_SUCESS"
const GET_PRODUCT_DETAILS_REQUEST_FAILUE = "GET_PRODUCT_DETAILS_REQUEST_FAILUE"

const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST"
const ADD_REVIEW_REQUEST_SUCESS = "ADD_REVIEW_REQUEST_SUCESS"
const ADD_REVIEW_REQUEST_FAILUE = "ADD_REVIEW_REQUEST_FAILUE"

const ADD_CART_REQUEST = "ADD_CART_REQUEST"
const ADD_CART_REQUEST_SUCESS = "ADD_CART_REQUEST_SUCESS"
const ADD_CART_REQUEST_FAILUE = "ADD_CART_REQUEST_FAILUE"

const GET_CART_REQUEST = "GET_CART_REQUEST"
const GET_CART_REQUEST_SUCESS = "GET_CART_REQUEST_SUCESS"
const GET_CART_REQUEST_FAILUE = "GET_CART_REQUEST_FAILUE"


const REMOVE_SINGLE_CART_REQUEST = "REMOVE_SINGLE_CART_REQUEST"
const REMOVE_SINGLE_CART_REQUEST_SUCESS = "REMOVE_SINGLE_CART_REQUEST_SUCESS"
const REMOVE_SINGLE_CART_REQUEST_FAILUE = "REMOVE_SINGLE_CART_REQUEST_FAILUE"


const REMOVE_ALL_CART_REQUEST = "REMOVE_ALL_CART_REQUEST"
const REMOVE_ALL_CART_REQUEST_SUCESS = "REMOVE_ALL_CART_REQUEST_SUCESS"
const REMOVE_ALL_CART_REQUEST_FAILUE = "REMOVE_ALL_CART_REQUEST_FAILUE"

const INCREMENT_CART_QUANTYTI_REQUEST = "INCREMENT_CART_QUANTYTI_REQUEST"
const INCREMENT_CART_QUANTYTI_REQUEST_SUCESS = "INCREMENT_CART_QUANTYTI_REQUEST_SUCESS"
const INCREMENT_CART_QUANTYTI_REQUEST_FAILUE = "INCREMENT_CART_QUANTYTI_REQUEST_FAILUE"

const DECREMENT_CART_QUANTYTI_REQUEST = "DECREMENT_CART_QUANTYTI_REQUEST"
const DECREMENT_CART_QUANTYTI_REQUEST_SUCESS = "DECREMENT_CART_QUANTYTI_REQUEST_SUCESS"
const DECREMENT_CART_QUANTYTI_REQUEST_FAILUE = "DECREMENT_CART_QUANTYTI_REQUEST_FAILUE"

const ADD_DELIVERY_ADDRESS_REQUEST = "ADD_DELIVERY_ADDRESS"
const ADD_DELIVERY_ADDRESS_SUCESS = "ADD_DELIVERY_ADDRESS"
const ADD_DELIVERY_ADDRESS_FAILURE = "ADD_DELIVERY_ADDRESS"



export {
    SIGNUP_REQUEST,
    SIGNUP_REQUEST_SUCESS,
    SIGNUP_REQUEST_FAILUE,

    LOGIN_REQUEST,
    LOGIN_REQUEST_SUCESS,
    LOGIN_REQUEST_FAILUE,

    FORGET_PASSWORD_REQUEST,
    FORGET_PASSWORD_REQUEST_SUCESS,
    FORGET_PASSWORD_REQUEST_FAILUE,

    RESET_PASSWORD_REQUEST,
    RESET_PASSWORD_REQUEST_SUCESS,
    RESET_PASSWORD_REQUEST_FAILUE,



    GET_PRODUCT_REQUEST,
    GET_PRODUCT_REQUEST_SUCESS,
    GET_PRODUCT_REQUEST_FAILUE,

    GET_PRODUCT_DETAILS_REQUEST,
    GET_PRODUCT_DETAILS_REQUEST_SUCESS,
    GET_PRODUCT_DETAILS_REQUEST_FAILUE,

    ADD_REVIEW_REQUEST,
    ADD_REVIEW_REQUEST_SUCESS,
    ADD_REVIEW_REQUEST_FAILUE,

    ADD_CART_REQUEST,
    ADD_CART_REQUEST_SUCESS,
    ADD_CART_REQUEST_FAILUE,

    GET_CART_REQUEST,
    GET_CART_REQUEST_SUCESS,
    GET_CART_REQUEST_FAILUE,

    REMOVE_SINGLE_CART_REQUEST,
    REMOVE_SINGLE_CART_REQUEST_SUCESS,
    REMOVE_SINGLE_CART_REQUEST_FAILUE,

    REMOVE_ALL_CART_REQUEST,
    REMOVE_ALL_CART_REQUEST_SUCESS,
    REMOVE_ALL_CART_REQUEST_FAILUE,

    INCREMENT_CART_QUANTYTI_REQUEST,
    INCREMENT_CART_QUANTYTI_REQUEST_SUCESS,
    INCREMENT_CART_QUANTYTI_REQUEST_FAILUE,

    DECREMENT_CART_QUANTYTI_REQUEST,
    DECREMENT_CART_QUANTYTI_REQUEST_SUCESS,
    DECREMENT_CART_QUANTYTI_REQUEST_FAILUE,

    ADD_DELIVERY_ADDRESS_REQUEST,
    ADD_DELIVERY_ADDRESS_SUCESS,
    ADD_DELIVERY_ADDRESS_FAILURE
}