export const productsData = [
    {
        id: 1,
        name: 'iPhone 12',
        brand: 'Apple',
        category: 'electronics',
        description: 'The latest iPhone with 5G technology.',
        image: 'https://rukminim1.flixcart.com/image/416/416/xif0q/television/y/n/l/-original-imagkbyeqf5zxt6e.jpeg?q=70',
        price: 999,
        rating: 5,
    },
    {
        id: 2,
        name: 'Samsung Galaxy S21',
        brand: 'Samsung',
        category: 'electronics',
        description: 'A powerful Android phone with an amazing camera.',
        image: 'https://rukminim1.flixcart.com/image/416/416/xif0q/television/y/n/l/-original-imagkbyeqf5zxt6e.jpeg?q=70',
        price: 799,
        rating: 4,
    },
    {
        id: 3,
        name: 'Samsung Galaxy S21',
        brand: 'Samsung',
        category: 'electronics',
        description: 'A powerful Android phone with an amazing camera.',
        image: 'https://rukminim1.flixcart.com/image/416/416/xif0q/television/y/n/l/-original-imagkbyeqf5zxt6e.jpeg?q=70',
        price: 799,
        rating: 4,
    },
    {
        id: 4,
        name: 'Samsung Galaxy S21',
        brand: 'Samsung',
        category: 'electronics',
        description: 'A powerful Android phone with an amazing camera.',
        image: 'https://rukminim1.flixcart.com/image/416/416/xif0q/television/y/n/l/-original-imagkbyeqf5zxt6e.jpeg?q=70',
        price: 799,
        rating: 4,
    },
    {
        id: 5,
        name: 'Samsung Galaxy S21',
        brand: 'Samsung',
        category: 'electronics',
        description: 'A powerful Android phone with an amazing camera.',
        image: 'https://rukminim1.flixcart.com/image/416/416/xif0q/television/y/n/l/-original-imagkbyeqf5zxt6e.jpeg?q=70',
        price: 799,
        rating: 4,
    },
    {
        id: 6,
        name: 'Samsung Galaxy S21',
        brand: 'Samsung',
        category: 'electronics',
        description: 'A powerful Android phone with an amazing camera.',
        image: 'https://rukminim1.flixcart.com/image/416/416/xif0q/television/y/n/l/-original-imagkbyeqf5zxt6e.jpeg?q=70',
        price: 799,
        rating: 4,
    },
   
];